version: '3.8'

services:
  hello-world-react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  default:
    name: hello-world-dev-network